#!/usr/bin/env dataviewer

[dataview]
type = "XY"
title = "Suite"
x_title = "x"
y_title = "y"
description = """
Suite
"""

[chart.1]
title = "Data1"

[chart.2]
title = "Data2"

[chart.3]
title = "Data3"

[chart.4]
title = "Data4"

[chart.5]
title = "Data5"

[chart.6]
title = "Data6"

[data]
1 = [
0, 0,
1, 1,
2, 2,
3, 4,
4, 8,
5, 16,
6, 32,
7, 64,
]
2 = [
0, 0,
1, 1.5,
2, 3,
3, 4,
4, 7,
5, 8,
6, 9,
7, 10,
]
3 = [
0, 0,
1, 2,
2, 4,
3, 6,
4, 8,
5, 10,
6, 12,
7, 14,
]
4 = [
0, 0,
1, 3,
2, 6,
3, 9,
4, 10,
5, 10.5,
6, 11,
7, 11,
]
5 = [
0, 5,
1, 3,
2, 2,
3, 1,
4, 0.5,
5, 0.25,
6, 0,
7, 0,
]
6 = [
0, 0,
1, 0.25,
2, 0.5,
3, 1,
4, 2,
5, 4,
6, 8,
7, 16,
]
