#!/usr/bin/env dataviewer

[dataview]
type = "XY"
title = "Suite"
x_title = "x"
y_title = "y"
description = """
Suite
"""

[chart.1]
title = "Data"

[data.1]
data = [
0, 0,
1, 1,
2, 2,
3, 4,
4, 8,
5, 16,
6, 32,
7, 64,
]

